cases:
    'y-piece':
        # Y-Piece
        ## radius = 0.76 mm

        ### bg rate 5 mlpmin
        'y-piece_r0.76mm_bg5mlpmin_in0mlpmin_o5cm_bg1cm_p5cm':
            radius_mm: 0.76
            bg_flow_mlpmin: 5
            inlet_flow_mlpmin: 0
            outlet_len_cm: 5
            bg_len_cm: 1  # length of background flow inlet
            inlet_len_cm: 5  # particle inlet length
            end_time_s: 0.8
            delta_time_s: 0.00025
            write_interval_steps: 400

        'y-piece_r0.76mm_bg5mlpmin_in5mlpmin_o5cm_bg1cm_p5cm':
            radius_mm: 0.76
            bg_flow_mlpmin: 5
            inlet_flow_mlpmin: 5
            outlet_len_cm: 5
            bg_len_cm: 1  # length of background flow inlet
            inlet_len_cm: 5  # particle inlet length
            end_time_s: 0.8
            delta_time_s: 0.0003
            write_interval_steps: 500

        'y-piece_r0.76mm_bg5mlpmin_in10mlpmin_o5cm_bg1cm_p5cm':
            radius_mm: 0.76
            bg_flow_mlpmin: 5
            inlet_flow_mlpmin: 10
            outlet_len_cm: 5
            bg_len_cm: 1  # length of background flow inlet
            inlet_len_cm: 5  # particle inlet length
            end_time_s: 0.8
            delta_time_s: 0.0002
            write_interval_steps: 500

        'y-piece_r0.76mm_bg5mlpmin_in16.6mlpmin_o5cm_bg1cm_p5cm':
            radius_mm: 0.76
            bg_flow_mlpmin: 5
            inlet_flow_mlpmin: 16.6
            outlet_len_cm: 5
            bg_len_cm: 1  # length of background flow inlet
            inlet_len_cm: 5  # particle inlet length
            end_time_s: 0.8
            delta_time_s: 0.0003
            write_interval_steps: 500

        ### bg rate 10 mlpmin
        'y-piece_r0.76mm_bg10mlpmin_in0mlpmin_o5cm_bg1cm_p5cm':
            radius_mm: 0.76
            bg_flow_mlpmin: 10
            inlet_flow_mlpmin: 0
            outlet_len_cm: 5
            bg_len_cm: 1  # length of background flow inlet
            inlet_len_cm: 5  # particle inlet length
            end_time_s: 0.8
            delta_time_s: 0.0003
            write_interval_steps: 500

        'y-piece_r0.76mm_bg10mlpmin_in5mlpmin_o5cm_bg1cm_p5cm':
            radius_mm: 0.76
            bg_flow_mlpmin: 10
            inlet_flow_mlpmin: 5
            outlet_len_cm: 5
            bg_len_cm: 1  # length of background flow inlet
            inlet_len_cm: 5  # particle inlet length
            end_time_s: 0.8
            delta_time_s: 0.0003
            write_interval_steps: 500

        'y-piece_r0.76mm_bg10mlpmin_in10mlpmin_o5cm_bg1cm_p5cm':
            radius_mm: 0.76
            bg_flow_mlpmin: 10
            inlet_flow_mlpmin: 10
            outlet_len_cm: 5
            bg_len_cm: 1  # length of background flow inlet
            inlet_len_cm: 5  # particle inlet length
            end_time_s: 0.8
            delta_time_s: 0.0003
            write_interval_steps: 500

        'y-piece_r0.76mm_bg10mlpmin_in16.6mlpmin_o5cm_bg1cm_p5cm':
            radius_mm: 0.76
            bg_flow_mlpmin: 10
            inlet_flow_mlpmin: 16.6
            outlet_len_cm: 5
            bg_len_cm: 1  # length of background flow inlet
            inlet_len_cm: 5  # particle inlet length
            end_time_s: 0.8
            delta_time_s: 0.0003
            write_interval_steps: 500

        ### bg rate 20 mlpmin
        'y-piece_r0.76mm_bg20mlpmin_in0mlpmin_o5cm_bg1cm_p5cm':
            radius_mm: 0.76
            bg_flow_mlpmin: 20
            inlet_flow_mlpmin: 0
            outlet_len_cm: 5
            bg_len_cm: 1  # length of background flow inlet
            inlet_len_cm: 5  # particle inlet length
            end_time_s: 0.8
            delta_time_s: 0.0003
            write_interval_steps: 500

        'y-piece_r0.76mm_bg20mlpmin_in5mlpmin_o5cm_bg1cm_p5cm':
            radius_mm: 0.76
            bg_flow_mlpmin: 20
            inlet_flow_mlpmin: 5
            outlet_len_cm: 5
            bg_len_cm: 1  # length of background flow inlet
            inlet_len_cm: 5  # particle inlet length
            end_time_s: 0.8
            delta_time_s: 0.0003
            write_interval_steps: 500

        'y-piece_r0.76mm_bg20mlpmin_in10mlpmin_o5cm_bg1cm_p5cm':
            radius_mm: 0.76
            bg_flow_mlpmin: 20
            inlet_flow_mlpmin: 10
            outlet_len_cm: 5
            bg_len_cm: 1  # length of background flow inlet
            inlet_len_cm: 5  # particle inlet length
            end_time_s: 0.8
            delta_time_s: 0.0003
            write_interval_steps: 500

        'y-piece_r0.76mm_bg20mlpmin_in16.6mlpmin_o5cm_bg1cm_p5cm':
            radius_mm: 0.76
            bg_flow_mlpmin: 20
            inlet_flow_mlpmin: 16.6
            outlet_len_cm: 5
            bg_len_cm: 1  # length of background flow inlet
            inlet_len_cm: 5  # particle inlet length
            end_time_s: 0.8
            delta_time_s: 0.0003
            write_interval_steps: 500

        ### intermediate flow speeds for pump ramp-down tests:
        'y-piece_r0.76mm_bg5mlpmin_in3.3mlpmin_o5cm_bg1cm_p5cm':
            radius_mm: 0.76
            bg_flow_mlpmin: 5
            inlet_flow_mlpmin: 3.333333333333333333
            outlet_len_cm: 5
            bg_len_cm: 1  # length of background flow inlet
            inlet_len_cm: 5  # particle inlet length
            end_time_s: 0.8
            delta_time_s: 0.0002
            write_interval_steps: 500

        'y-piece_r0.76mm_bg5mlpmin_in6.7mlpmin_o5cm_bg1cm_p5cm':
            radius_mm: 0.76
            bg_flow_mlpmin: 5
            inlet_flow_mlpmin: 6.666666666666666666
            outlet_len_cm: 5
            bg_len_cm: 1  # length of background flow inlet
            inlet_len_cm: 5  # particle inlet length
            end_time_s: 0.8
            delta_time_s: 0.0002
            write_interval_steps: 500


        ## radius = 0.75 mm
        ### off or on:
        #### 4 cm outlet, 1 cm bg inlet, 4 cm particle inlet:
        'y-piece_r0.75mm_bg5mlpmin_in0mlpmin_o4cm_bg1cm_p4cm':
            radius_mm: 0.75
            bg_flow_mlpmin: 5
            inlet_flow_mlpmin: 0
            outlet_len_cm: 4
            bg_len_cm: 1  # length of background flow inlet
            inlet_len_cm: 4  # particle inlet length
            end_time_s: 0.8
            delta_time_s: 0.00025
            write_interval_steps: 400

        'y-piece_r0.75mm_bg5mlpmin_in10mlpmin_o4cm_bg1cm_p4cm':
            radius_mm: 0.75
            bg_flow_mlpmin: 5
            inlet_flow_mlpmin: 10
            outlet_len_cm: 4
            bg_len_cm: 1  # length of background flow inlet
            inlet_len_cm: 4  # particle inlet length
            end_time_s: 0.8
            delta_time_s: 0.0002
            write_interval_steps: 500

        #### refined variant, 4 cm outlet, 1 cm bg inlet, 4 cm particle inlet:
        'y-piece_r0.75mm_bg5mlpmin_in0mlpmin_o4cm_bg1cm_p4cm_refined':
            radius_mm: 0.75
            bg_flow_mlpmin: 5
            inlet_flow_mlpmin: 0
            outlet_len_cm: 4
            bg_len_cm: 1  # length of background flow inlet
            inlet_len_cm: 4  # particle inlet length
            variant: refined
            end_time_s: 0.8
            delta_time_s: 0.00025
            write_interval_steps: 400

        'y-piece_r0.75mm_bg5mlpmin_in10mlpmin_o4cm_bg1cm_p4cm_refined':
            radius_mm: 0.75
            bg_flow_mlpmin: 5
            inlet_flow_mlpmin: 10
            outlet_len_cm: 4
            bg_len_cm: 1  # length of background flow inlet
            inlet_len_cm: 4  # particle inlet length
            variant: refined
            end_time_s: 0.8
            delta_time_s: 0.0002
            write_interval_steps: 500

        #### 7 cm outlet, 1 cm bg inlet, 4 cm particle inlet:
        'y-piece_r0.75mm_bg5mlpmin_in0mlpmin_o7cm_bg1cm_p4cm':
            radius_mm: 0.75
            bg_flow_mlpmin: 5
            inlet_flow_mlpmin: 0
            outlet_len_cm: 7
            bg_len_cm: 1  # length of background flow inlet
            inlet_len_cm: 4  # particle inlet length
            end_time_s: 0.8
            delta_time_s: 0.00025
            write_interval_steps: 400

        'y-piece_r0.75mm_bg5mlpmin_in10mlpmin_o7cm_bg1cm_p4cm':
            radius_mm: 0.75
            bg_flow_mlpmin: 5
            inlet_flow_mlpmin: 10
            outlet_len_cm: 7
            bg_len_cm: 1  # length of background flow inlet
            inlet_len_cm: 4  # particle inlet length
            end_time_s: 0.8
            delta_time_s: 0.0002
            write_interval_steps: 500

        #### 5 cm outlet, 5 cm bg inlet, 9 cm particle inlet:
        'y-piece_r0.75mm_bg5mlpmin_in0mlpmin_o5cm_bg5cm_p9cm':
            radius_mm: 0.75
            bg_flow_mlpmin: 5
            inlet_flow_mlpmin: 0
            outlet_len_cm: 5
            bg_len_cm: 5  # length of background flow inlet
            inlet_len_cm: 9  # particle inlet length
            end_time_s: 0.8
            delta_time_s: 0.00025
            write_interval_steps: 400

        'y-piece_r0.75mm_bg5mlpmin_in10mlpmin_o5cm_bg5cm_p9cm':
            radius_mm: 0.75
            bg_flow_mlpmin: 5
            inlet_flow_mlpmin: 10
            outlet_len_cm: 5
            bg_len_cm: 5  # length of background flow inlet
            inlet_len_cm: 9  # particle inlet length
            end_time_s: 0.8
            delta_time_s: 0.0002
            write_interval_steps: 500

    tube:
        'tube_r0.76mm_l15cm_3.3mlpmin_11cells':
            # 1st/2 intermediate step from 0 mlpmin to 10 mlpmin
            # TODO: test convergence
            radius_mm: 0.76
            flow_mlpmin: 3.33333333333333333333
            len_cm: 15
            end_time_s: 1.2
            delta_time_s: 0.0005
            write_interval_steps: 200
            cells: 11
        'tube_r0.76mm_l15cm_5mlpmin_11cells':
            radius_mm: 0.76
            flow_mlpmin: 5
            len_cm: 15
            end_time_s: 1.05
            delta_time_s: 0.0005
            write_interval_steps: 200
            cells: 11
        'tube_r0.76mm_l15cm_6.7mlpmin_11cells':
            # 2nd/2 intermediate step from 0 mlpmin to 10 mlpmin
            radius_mm: 0.76
            flow_mlpmin: 6.66666666666666666667
            len_cm: 15
            end_time_s: 1.2
            delta_time_s: 0.0005
            write_interval_steps: 200
            cells: 11
        'tube_r0.76mm_l15cm_8.3mlpmin_11cells':
            # 1st/2 intermediate step from 5 mlpmin to 15 mlpmin
            radius_mm: 0.76
            flow_mlpmin: 8.33333333333333333333
            len_cm: 15
            end_time_s: 1.2
            delta_time_s: 0.0005
            write_interval_steps: 200
            cells: 11
        'tube_r0.76mm_l15cm_10mlpmin_11cells':
            radius_mm: 0.76
            flow_mlpmin: 10
            len_cm: 15
            end_time_s: 1.2
            delta_time_s: 0.0005
            write_interval_steps: 200
            cells: 11
        'tube_r0.76mm_l15cm_11.7mlpmin_11cells':
            # 2nd/2 intermediate step from 5 mlpmin to 15 mlpmin
            radius_mm: 0.76
            flow_mlpmin: 11.6666666666666666667
            len_cm: 15
            end_time_s: 1.2
            delta_time_s: 0.0005
            write_interval_steps: 200
            cells: 11
        'tube_r0.76mm_l15cm_15mlpmin_11cells':
            radius_mm: 0.76
            flow_mlpmin: 15
            len_cm: 15
            end_time_s: 1.2
            delta_time_s: 0.0005
            write_interval_steps: 200
            cells: 11
        'tube_r0.76mm_l15cm_16.6mlpmin_11cells':
            radius_mm: 0.76
            flow_mlpmin: 16.6
            len_cm: 15
            end_time_s: 1.2
            delta_time_s: 0.0005
            write_interval_steps: 200
            cells: 11
        'tube_r0.76mm_l15cm_20mlpmin_11cells':
            radius_mm: 0.76
            flow_mlpmin: 20
            len_cm: 15
            end_time_s: 1.2
            delta_time_s: 0.0005
            write_interval_steps: 200
            cells: 11
        'tube_r0.76mm_l15cm_21.6mlpmin_11cells':
            radius_mm: 0.76
            flow_mlpmin: 21.6
            len_cm: 15
            end_time_s: 1.2
            delta_time_s: 0.0005
            write_interval_steps: 200
            cells: 11
        'tube_r0.76mm_l15cm_25mlpmin_11cells':
            radius_mm: 0.76
            flow_mlpmin: 25
            len_cm: 15
            end_time_s: 1.2
            delta_time_s: 0.0005
            write_interval_steps: 200
            cells: 11
        'tube_r0.76mm_l15cm_26.6mlpmin_11cells':
            radius_mm: 0.76
            flow_mlpmin: 26.6
            len_cm: 15
            end_time_s: 1.2
            delta_time_s: 0.0005
            write_interval_steps: 200
            cells: 11
        'tube_r0.76mm_l15cm_30mlpmin_11cells':
            radius_mm: 0.76
            flow_mlpmin: 30
            len_cm: 15
            end_time_s: 1.2
            delta_time_s: 0.0005
            write_interval_steps: 200
            cells: 11
        'tube_r0.76mm_l15cm_36mlpmin_11cells':
            radius_mm: 0.76
            flow_mlpmin: 36
            len_cm: 15
            end_time_s: 1.2
            delta_time_s: 0.0005
            write_interval_steps: 200
            cells: 11
        'tube_r0.76mm_l15cm_36.6mlpmin_11cells':
            radius_mm: 0.76
            flow_mlpmin: 36.6
            len_cm: 15
            end_time_s: 1.2
            delta_time_s: 0.0005
            write_interval_steps: 200
            cells: 11
