#!/bin/sh

cd ${0%/*} || exit 1  # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions  # Tutorial run functions

# Assuming that ./ConstructMesh has been run
restore0Dir  # assumes 0.orig/ exists

runApplication -s sim decomposePar
#runApplication -s sim $(getApplication)
runApplication -s sim mpirun -np 8 $(getApplication) -parallel
runApplication -s sim reconstructPar

rm -rf ./processor*
