#!/bin/sh

cd ${0%/*} || exit 1  # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions  # Tutorial run functions

# Rename 0/ (containing our initial configuration) to 0.org/ so it won't
# be overwritten during the snappyHexMesh workflow.
# (TODO: Is this still an issue? (cp. YouTube tutorial))
#mv 0 0.orig
# Assuming 0.orig always contains the correct files for the actual simulation
# (i.e., not for mesh generation) and is committed to git.
# --> No need to move/copy contents of 0/ to 0.org/.

runApplication -s mesh blockMesh
runApplication -s mesh surfaceFeatureExtract
runApplication -s mesh decomposePar
runApplication -s mesh mpirun -np 8 snappyHexMesh -overwrite -parallel
#runParallel -s mesh snappyHexMesh -overwrite -parallel  # ?
runApplication -s mesh reconstructParMesh -constant
rm -rf ./processor*

runApplication -s mesh checkMesh

#rm -rf 0
#cp 0.orig 0
#restore0Dir  # assumes 0.orig/ exists -> now in RunSimulation
