#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

runApplication blockMesh
runApplication decomposePar
#runApplication $(getApplication)
runApplication mpirun -np 4 $(getApplication) -parallel
runApplication reconstructPar
runApplication postProcess -func writeCellCentres -latestTime

#------------------------------------------------------------------------------
